# Save nested JSON to a Pandas Dataframe

In [7]:
import pandas as pd
import json
from pprint import pprint as pp

In [8]:
with open('brian_sample.json') as brian_in:
    raw_data = json.load(brian_in)
pp(raw_data)

{'asset': 'BTC',
 'assetReference': 'asset-v2:bip122:000000000019d6689c085ae165831e93:native',
 'blockHash': '000000000000000000016e374842bf4e8324871952f7868823acf4133047ab01',
 'blockHeight': 824883,
 'blockTimestamp': '2024-01-08T16:24:16Z',
 'exchangeRate': 44991.52,
 'fee': 0.0006747,
 'traces': [{'inputs': [{'address': 'bc1qwfn4fq5l86snpddxa7wy9jh6dc86vd6jdquw2g',
                         'amount': 5.46e-06,
                         'category': None,
                         'name': None,
                         'rootAddress': 'bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr'},
                        {'address': 'bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr',
                         'amount': 0.04775618,
                         'category': None,
                         'name': None,
                         'rootAddress': 'bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr'}],
             'outputs': [{'address': 'bc1qflc0slh4n7jk903kh55f7s9aly3dcdh4k7gm97',
                          'amount': 5.46e-06,
                          'category': None,
                          'name': None,
                          'rootAddress': 'bc1qflc0slh4n7jk903kh55f7s9aly3dcdh4k7gm97'},
                         {'address': 'bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr',
                          'amount': 0.04708148,
                          'category': None,
                          'name': None,
                          'rootAddress': 'bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr'}]}],
 'transactionHash': 'fa868899d19dde40b022dd76fb4ac9a4ed02db6a7d70a0be87a1776d77811360'}

In [28]:
fields = list(raw_data.keys())
fields.remove('traces')

df_inputs = pd.json_normalize(
    raw_data,
    record_path=["traces", "inputs"],
    meta = fields,
)
df_inputs['side'] = ["inputs"] * len(df_inputs)

df_outputs = pd.json_normalize(
    raw_data,
    record_path=["traces", "outputs"],
    meta = fields,
)
df_outputs['side'] = ["outputs"] * len(df_outputs)

df = pd.concat([df_inputs, df_outputs])
df

,address,rootAddress,name,category,amount,asset,assetReference,transactionHash,blockTimestamp,blockHash,blockHeight,exchangeRate,fee,side
0,bc1qwfn4fq5l86snpddxa7wy9jh6dc86vd6jdquw2g,bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr,None,None,0.000005,BTC,asset-v2:bip122:000000000019d6689c085ae165831e...,fa868899d19dde40b022dd76fb4ac9a4ed02db6a7d70a0...,2024-01-08T16:24:16Z,000000000000000000016e374842bf4e8324871952f786...,824883,44991.52,0.000675,inputs
1,bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr,bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr,None,None,0.047756,BTC,asset-v2:bip122:000000000019d6689c085ae165831e...,fa868899d19dde40b022dd76fb4ac9a4ed02db6a7d70a0...,2024-01-08T16:24:16Z,000000000000000000016e374842bf4e8324871952f786...,824883,44991.52,0.000675,inputs
0,bc1qflc0slh4n7jk903kh55f7s9aly3dcdh4k7gm97,bc1qflc0slh4n7jk903kh55f7s9aly3dcdh4k7gm97,None,None,0.000005,BTC,asset-v2:bip122:000000000019d6689c085ae165831e...,fa868899d19dde40b022dd76fb4ac9a4ed02db6a7d70a0...,2024-01-08T16:24:16Z,000000000000000000016e374842bf4e8324871952f786...,824883,44991.52,0.000675,outputs
1,bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr,bc1qjguxrqjx9qnpmklzymdr0y6mqxrth9d3swzdpr,None,None,0.047081,BTC,asset-v2:bip122:000000000019d6689c085ae165831e...,fa868899d19dde40b022dd76fb4ac9a4ed02db6a7d70a0...,2024-01-08T16:24:16Z,000000000000000000016e374842bf4e8324871952f786...,824883,44991.52,0.000675,outputs